  version: "2"
  services:

    apigateway:
      build: ./zuul-api-gateway
      restart: always
      network_mode: host
      depends_on:
        - eurekaserver


    eurekaserver:
      build: ./spring-eureka-server
      restart: always
      network_mode: host


    configserver:
      build: ./track-config-server
      restart: always
      network_mode: host

    userservice:
        build: ./userService
        restart: always
        network_mode: host
        depends_on:
          - mysql
          - eurekaserver

    trackservice:
      build: ./trackService
      restart: always
      network_mode: host
      depends_on:
        - eurekaserver

    mongo:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      network_mode: host
      volumes:
        - $HOME/mongo/db:/data/db

    mysql:
      image: mysql:5.7
      ports:
        - 3306:3306
      expose:
        - 3306
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_DATABASE: userdb
        MYSQL_PASSWORD: root123
        MYSQL_USER: root
      network_mode: "host"
      hostname: localhost
      restart: always
      volumes:
        - /$HOME/mysql:/var/lib/mysql

